version: '3.7'

services:
  nhabanhoa_db:
    container_name: "db_test_nhabanhoa"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./database/docker/dev/Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "db_test_nhabanhoa"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  cache:
    container_name: "cache_test_nhabanhoa"
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
networks:
  default:
volumes:
  mysql_data:
  cache:
    driver: local