// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type DetailItem struct {
	ID         int              `json:"id"`
	Name       string           `json:"name"`
	Attributes []*OverviewLabel `json:"attributes"`
	Images     []*OverviewImage `json:"images"`
}

type ItemFilter struct {
	Attributes []int `json:"attributes"`
}

type NewCollection struct {
	Name string `json:"name"`
}

type NewImage struct {
	Link string `json:"link"`
}

type NewItem struct {
	Name       string `json:"name"`
	SearchKeys string `json:"searchKeys"`
	Attributes []int  `json:"attributes"`
	Images     []int  `json:"images"`
	Type       int    `json:"type"`
}

type NewLabel struct {
	Code    string `json:"code"`
	Value   string `json:"value"`
	FkLabel *int   `json:"fkLabel"`
	Active  bool   `json:"active"`
}

type NewRole struct {
	Label       string  `json:"label"`
	Description *string `json:"description"`
	Active      bool    `json:"active"`
}

type NewUser struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	Active      bool   `json:"active"`
	DisplayName string `json:"displayName"`
	Address     string `json:"address"`
	PhoneNumber string `json:"phoneNumber"`
	CountryCode int    `json:"countryCode"`
	Role        int    `json:"role"`
	Status      int    `json:"status"`
}

type OverviewCollection struct {
	ID        int    `json:"id"`
	Name      string `json:"name"`
	Order     int    `json:"order"`
	TotalItem int    `json:"totalItem"`
}

type OverviewImage struct {
	ID   int    `json:"id"`
	Link string `json:"link"`
}

type OverviewItem struct {
	ID     int            `json:"id"`
	Name   string         `json:"name"`
	Avatar *OverviewImage `json:"avatar"`
}

type OverviewLabel struct {
	ID        int              `json:"id"`
	Code      string           `json:"code"`
	Value     string           `json:"value"`
	SubLabels []*OverviewLabel `json:"subLabels"`
}

type OverviewRole struct {
	ID          int     `json:"id"`
	Label       string  `json:"label"`
	Description *string `json:"description"`
}

type OverviewUser struct {
	ID          int            `json:"id"`
	Username    string         `json:"username"`
	Active      bool           `json:"active"`
	DisplayName string         `json:"displayName"`
	Address     string         `json:"address"`
	PhoneNumber string         `json:"phoneNumber"`
	CountryCode *OverviewLabel `json:"countryCode"`
	Role        *OverviewRole  `json:"role"`
	Status      *OverviewLabel `json:"status"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type Pagination struct {
	Collections []int       `json:"collections"`
	Page        int         `json:"page"`
	Size        int         `json:"size"`
	Keyword     *string     `json:"keyword"`
	Filter      *ItemFilter `json:"filter"`
}
